### ISSUE TITLE
Not start blocking

### ISSUE THREAD

**Issue by keita-sunada** [connorkuljis/block-cli#9]
Hi, I'm a mac OS user and built your program from the source. 
I failed to start the blocking, so I appreciate if you could give me an advice. 

I just pasted your example lists to `/etc/hosts` then ran `block start 0.1 'test' -d`.
This gives the followings. Do I miss something? Thanks. 

```
2024/04/28 19:18:06 Checking: /Users/username/.config/block-cli
2024/04/28 19:18:06 Checking: /Users/username/.block-cli
2024/04/28 19:18:06 Loading config:  &{/Users/username/.config/block-cli config.yaml {. 1:0}}
2024/04/28 19:18:06 Loaded config.
2024/04/28 19:18:06 Loaded db.
## capture (bool): false
## blocker (bool): true
enabling blocker
--- social media
0.0.0.0 twitter.com
0.0.0.0 www.youtube.com
0.0.0.0 www.instagram.com
0.0.0.0 www.reddit.com
0.0.0.0 reddit.com
0.0.0.0 www.old.reddit.com
0.0.0.0 old.reddit.com
0.0.0.0 www.facebook.com
# ~ <-- lines below this character will be untouched by block-cli```

**Comment by connorkuljis** [comment]
Hi, sometimes you need to reset the DNS cache.

[https://superuser.com/questions/203674/how-to-clear-flush-the-dns-cache-in-google-chrome](https://superuser.com/questions/203674/how-to-clear-flush-the-dns-cache-in-google-chrome)

**Comment by keita-sunada** [comment]
I don't think my issue come from DNS cache.. I considered a case that I made something wrong for installation, so I did it again for ver0.19.  
Then after `block start 0.1 test -d`, I received `open /etc/hosts: permission denied` (putting sudo doesn't help me). 
I'm a beginner programmer, and I realize I'm not mature enough to handle this program. Anyway thanks for your reply & attention.
